{
 "title": "TLS Report",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Reportet mails over time",
   "type": "timeseries",
   "description": "Shows successful and failed mails reported over the given time",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "tlsreport",
     "rawSql": "SELECT successful AS \"Success\", failure AS \"Failed\", starttime AS \"time\" FROM tlsreport.reports LIMIT 50 "
    }
   ]
  },
  {
   "title": "Success-Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tlsreport",
     "rawSql": "SELECT SUM(successful) AS \"Success\", SUM(failure) AS \"Failed\" FROM tlsreport.reports WHERE $__timeFilter(starttime) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Reports by Sender-Domain",
   "type": "table",
   "description": "Number of reports, successful and failed mails sorted by Sender-Domain",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "tlsreport",
     "rawSql": "SELECT\n  d.domain AS `Sender Domain`,\n  o.name AS Organization,\n  COUNT(r.id) AS Reports,\n  SUM(r.successful) AS Success,\n  SUM(r.failure) AS Failure\nFROM\n  reports r\nJOIN\n  domains d ON r.senderdomain = d.id\nJOIN\n  organizations o ON r.organization = o.id\nWHERE\n  r.starttime >= $__timeFrom()\n  AND r.endtime <= $__timeTo()\nGROUP BY\n  d.domain, o.name\nORDER BY\n  Reports DESC;\n"
    }
   ]
  },
  {
   "title": "Reports by Receiver-Domain",
   "type": "table",
   "description": "Number of reports, successful and failed mails sorted by receiving domain",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "tlsreport",
     "rawSql": "SELECT\n  d.domain AS `Receiver Domain`,\n  COUNT(r.id) AS Reports,\n  SUM(r.successful) AS Success,\n  SUM(r.failure) AS Failure\nFROM\n  reports r\nJOIN\n  domains d ON r.receiverdomain = d.id\nWHERE\n  r.starttime >= $__timeFrom()\n  AND r.endtime <= $__timeTo()\nGROUP BY\n  d.domain\nORDER BY\n  Reports DESC;\n"
    }
   ]
  }
 ]
}